-- Archive roles: past presidents and captains
-- Seeded from data/archive-roles.ts (1977–2026)

CREATE TABLE IF NOT EXISTS public.archive_roles (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  role_type   text        NOT NULL CHECK (role_type IN ('president', 'captain')),
  year        int         NOT NULL,
  name        text        NOT NULL DEFAULT 'TBD',
  note        text,
  sort_order  int,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (role_type, year)
);

ALTER TABLE public.archive_roles ENABLE ROW LEVEL SECURITY;

-- Authenticated members can read
CREATE POLICY "Authenticated read archive_roles"
  ON public.archive_roles FOR SELECT
  TO authenticated
  USING (true);

-- Seed: Presidents (2026 → 1977)
INSERT INTO public.archive_roles (role_type, year, name, note) VALUES
  ('president', 2026, 'Judith Heaton',      null),
  ('president', 2025, 'Jeremy Frearson',    null),
  ('president', 2024, 'Catherine Mitrenas', null),
  ('president', 2023, 'Gerry Summers',      null),
  ('president', 2022, 'John Stutfield',     null),
  ('president', 2021, 'Ginnette Grimes',    null),
  ('president', 2020, 'Annie Watts',        null),
  ('president', 2019, 'Gary Lowry',         null),
  ('president', 2018, 'Maggie Bell',        'Voted in by membership as no president in post to gift as per constitution'),
  ('president', 2017, 'Pete Rees',          'Stepped down mid-season'),
  ('president', 2016, 'Jeremy Fordham',     null),
  ('president', 2015, 'Dinshaw Jilla',      null),
  ('president', 2014, 'Gareth Ballance',    null),
  ('president', 2013, 'Neale Freeland',     null),
  ('president', 2012, 'George Papanicola',  null),
  ('president', 2011, 'Frank Grimes',       null),
  ('president', 2010, 'Roger McGough',      null),
  ('president', 2009, 'TBD', null),
  ('president', 2008, 'TBD', null),
  ('president', 2007, 'TBD', null),
  ('president', 2006, 'TBD', null),
  ('president', 2005, 'TBD', null),
  ('president', 2004, 'TBD', null),
  ('president', 2003, 'TBD', null),
  ('president', 2002, 'TBD', null),
  ('president', 2001, 'TBD', null),
  ('president', 2000, 'TBD', null),
  ('president', 1999, 'TBD', null),
  ('president', 1998, 'TBD', null),
  ('president', 1997, 'TBD', null),
  ('president', 1996, 'TBD', null),
  ('president', 1995, 'TBD', null),
  ('president', 1994, 'TBD', null),
  ('president', 1993, 'TBD', null),
  ('president', 1992, 'TBD', null),
  ('president', 1991, 'TBD', null),
  ('president', 1990, 'TBD', null),
  ('president', 1989, 'TBD', null),
  ('president', 1988, 'TBD', null),
  ('president', 1987, 'TBD', null),
  ('president', 1986, 'TBD', null),
  ('president', 1985, 'TBD', null),
  ('president', 1984, 'TBD', null),
  ('president', 1983, 'TBD', null),
  ('president', 1982, 'TBD', null),
  ('president', 1981, 'TBD', null),
  ('president', 1980, 'TBD', null),
  ('president', 1979, 'TBD', null),
  ('president', 1978, 'TBD', null),
  ('president', 1977, 'TBD', null),

-- Seed: Captains (2026 → 1977)
  ('captain', 2026, 'Alaric Evans', null),
  ('captain', 2025, 'Alaric Evans', null),
  ('captain', 2024, 'Annie Watts',  null),
  ('captain', 2023, 'Annie Watts',  null),
  ('captain', 2022, 'TBD', null),
  ('captain', 2021, 'TBD', null),
  ('captain', 2020, 'TBD', null),
  ('captain', 2019, 'TBD', null),
  ('captain', 2018, 'TBD', null),
  ('captain', 2017, 'TBD', null),
  ('captain', 2016, 'TBD', null),
  ('captain', 2015, 'TBD', null),
  ('captain', 2014, 'TBD', null),
  ('captain', 2013, 'TBD', null),
  ('captain', 2012, 'TBD', null),
  ('captain', 2011, 'TBD', null),
  ('captain', 2010, 'TBD', null),
  ('captain', 2009, 'TBD', null),
  ('captain', 2008, 'TBD', null),
  ('captain', 2007, 'TBD', null),
  ('captain', 2006, 'TBD', null),
  ('captain', 2005, 'TBD', null),
  ('captain', 2004, 'TBD', null),
  ('captain', 2003, 'TBD', null),
  ('captain', 2002, 'TBD', null),
  ('captain', 2001, 'TBD', null),
  ('captain', 2000, 'TBD', null),
  ('captain', 1999, 'TBD', null),
  ('captain', 1998, 'TBD', null),
  ('captain', 1997, 'TBD', null),
  ('captain', 1996, 'TBD', null),
  ('captain', 1995, 'TBD', null),
  ('captain', 1994, 'TBD', null),
  ('captain', 1993, 'TBD', null),
  ('captain', 1992, 'TBD', null),
  ('captain', 1991, 'TBD', null),
  ('captain', 1990, 'TBD', null),
  ('captain', 1989, 'TBD', null),
  ('captain', 1988, 'TBD', null),
  ('captain', 1987, 'TBD', null),
  ('captain', 1986, 'TBD', null),
  ('captain', 1985, 'TBD', null),
  ('captain', 1984, 'TBD', null),
  ('captain', 1983, 'TBD', null),
  ('captain', 1982, 'TBD', null),
  ('captain', 1981, 'TBD', null),
  ('captain', 1980, 'TBD', null),
  ('captain', 1979, 'TBD', null),
  ('captain', 1978, 'TBD', null),
  ('captain', 1977, 'TBD', null)
ON CONFLICT (role_type, year) DO NOTHING;
